# Import Library

In [25]:
import pandas as pd
import numpy as np
from scipy import stats

In [26]:
def transform_to_array(dataframe: pd.DataFrame):
    return dataframe.to_numpy().transpose()

In [27]:
def evaluate_pvalue(pvalue: float, alpha=0.05) -> str:
    return "Reject H0" if pvalue < alpha else "NOT Reject H0"

# Reject H0     -> the difference in the distribution of the observed data is significant
# NOT Reject H0 -> the difference in the distribution of the observed data is NOT significant

In [28]:
def generate_description(pvalue, alpha=0.05):
    output = "the difference in the distribution of the observed data is"
    output.join(" significant") if pvalue < alpha else output.join(" NOT significant")
    return output

# Create Result Report

In [29]:
report_df = pd.DataFrame(columns=['Test Name','statistic','P-Value','Result(Alpha=0.05)', 'Description'])
report_df

Empty DataFrame
Columns: [Test Name, statistic, P-Value, Result(Alpha=0.05), Description]
Index: []

In [30]:
overall_table = pd.read_csv('table/overall_tab.csv')
overall_table = overall_table.drop(["chapter"], axis=1)
overall_table

        ED     IPD
0   252201  370060
1    98659  151677
2    95028  732435
3    84982  162558
4    64489  556969
5    56951  191518
6    48131  322429
7    46463  731055
8    39539  315114
9    39200  227362
10   34869  180230
11   18380   61208
12   15917  182196
13   12002  105926
14    9309  171510
15    7808  112388
16    6926   74459
17    5414   30793
18    2962    8284
19     355   11472
20       9      59

In [31]:
transformed_data = transform_to_array(overall_table)
print(transformed_data)
results = stats.chi2_contingency(transformed_data)

pvalue_result = results.pvalue
print(results)
print("pvalue:",pvalue_result)
print("statistic:",results.statistic)
print(evaluate_pvalue(pvalue_result))

[[252201  98659  95028  84982  64489  56951  48131  46463  39539  39200
   34869  18380  15917  12002   9309   7808   6926   5414   2962    355
       9]
 [370060 151677 732435 162558 556969 191518 322429 731055 315114 227362
  180230  61208 182196 105926 171510 112388  74459  30793   8284  11472
      59]]
Chi2ContingencyResult(statistic=np.float64(570072.3305872576), pvalue=np.float64(0.0), dof=20, expected_freq=array([[1.03678314e+05, 4.17098524e+04, 1.37868143e+05, 4.12439955e+04,
        1.03544522e+05, 4.13987813e+04, 6.17410316e+04, 1.29546533e+05,
        5.90906792e+04, 4.44133551e+04, 3.58388228e+04, 1.32605927e+04,
        3.30086922e+04, 1.96486301e+04, 3.01272442e+04, 2.00265140e+04,
        1.35600007e+04, 6.03264662e+03, 1.87375767e+03, 1.97056126e+03,
        1.13298525e+01],
       [5.18582686e+05, 2.08626148e+05, 6.89594857e+05, 2.06296005e+05,
        5.17913478e+05, 2.07070219e+05, 3.08818968e+05, 6.47971467e+05,
        2.95562321e+05, 2.22148645e+05, 1.79260177e+05, 6.63274073e+04,
        1.65104308e+05, 9.82793699e+04, 1.50691756e+05, 1.00169486e+05,
        6.78249993e+04, 3.01743534e+04, 9.37224233e+03, 9.85643874e+03,
        5.66701475e+01]]))
pvalue: 0.0
statistic: 570072.3305872576
Reject H0

In [32]:
result_hypothesis = evaluate_pvalue(results.pvalue)
results_des = generate_description(results.pvalue)

In [33]:
new_row = {
    'Test Name': 'overall_chapter',
    'statistic': results.statistic,
    'P-Value': results.pvalue,
    'Result(Alpha=0.05)': result_hypothesis, 
    'Description': results_des
}

report_df = pd.concat([report_df, pd.DataFrame([new_row])], ignore_index=True)
report_df

C:\Users\User\AppData\Local\Temp\ipykernel_19720\3305976903.py:9: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  report_df = pd.concat([report_df, pd.DataFrame([new_row])], ignore_index=True)

,Test Name,statistic,P-Value,Result(Alpha=0.05),Description
0,overall_chapter,570072.330587,0.0,Reject H0,the difference in the distribution of the obse...

In [34]:
for i in range(1,22):
    table = pd.read_csv(f'table/tab_chapter{i}.csv')
    table = table.drop(["icd_code"], axis=1)
    
    transformed_data = transform_to_array(table)
    results = stats.chi2_contingency(transformed_data)

    statistic = results.statistic
    pvalue = results.pvalue
    result_hypothesis = evaluate_pvalue(pvalue)
    results_des = generate_description(pvalue)

    new_row = {
        'Test Name': f'tab_chapter{i}',
        'statistic': statistic,
        'P-Value': pvalue,
        'Result(Alpha=0.05)': result_hypothesis, 
        'Description': results_des
    }
    report_df = pd.concat([report_df, pd.DataFrame([new_row])], ignore_index=True)

In [35]:
report_df

,Test Name,statistic,P-Value,Result(Alpha=0.05),Description
0,overall_chapter,570072.330587,0.000000e+00,Reject H0,the difference in the distribution of the obse...
1,tab_chapter1,26789.108421,0.000000e+00,Reject H0,the difference in the distribution of the obse...
2,tab_chapter2,11019.766350,0.000000e+00,Reject H0,the difference in the distribution of the obse...
3,tab_chapter3,14144.621625,0.000000e+00,Reject H0,the difference in the distribution of the obse...
4,tab_chapter4,101539.618777,0.000000e+00,Reject H0,the difference in the distribution of the obse...
5,tab_chapter5,62211.904463,0.000000e+00,Reject H0,the difference in the distribution of the obse...
6,tab_chapter6,32887.807794,0.000000e+00,Reject H0,the difference in the distribution of the obse...
7,tab_chapter7,14303.288138,0.000000e+00,Reject H0,the difference in the distribution of the obse...
8,tab_chapter8,4975.338873,0.000000e+00,Reject H0,the difference in the distribution of the obse...
9,tab_chapter9,103018.384431,0.000000e+00,Reject H0,the difference in the distribution of the obse...
10,tab_chapter10,64104.023011,0.000000e+00,Reject H0,the difference in the distribution of the obse...
11,tab_chapter11,86956.690300,0.000000e+00,Reject H0,the difference in the distribution of the obse...
12,tab_chapter12,16386.255327,0.000000e+00,Reject H0,the difference in the distribution of the obse...
13,tab_chapter13,93660.011395,0.000000e+00,Reject H0,the difference in the distribution of the obse...
14,tab_chapter14,50545.269241,0.000000e+00,Reject H0,the difference in the distribution of the obse...
15,tab_chapter15,47893.122395,0.000000e+00,Reject H0,the difference in the distribution of the obse...
16,tab_chapter16,61.468927,1.181969e-06,Reject H0,the difference in the distribution of the obse...
17,tab_chapter17,1318.907039,8.317674e-99,Reject H0,the difference in the distribution of the obse...
18,tab_chapter18,172442.354419,0.000000e+00,Reject H0,the difference in the distribution of the obse...
19,tab_chapter19,89434.003124,0.000000e+00,Reject H0,the difference in the distribution of the obse...
20,tab_chapter20,114790.698028,0.000000e+00,Reject H0,the difference in the distribution of the obse...
21,tab_chapter21,150851.496086,0.000000e+00,Reject H0,the difference in the distribution of the obse...

In [36]:
report_df.to_csv('chi2_results.csv', header=True, index=False)