In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./table/overall_tab.csv')
df = df.sort_values(by='chapter')

In [3]:
chi_result = pd.read_csv('chi2_results.csv')
chi_result

,Test Name,statistic,P-Value,Result(Alpha=0.05),Description
0,overall_chapter,570072.330587,0.000000e+00,Reject H0,the difference in the distribution of the obse...
1,tab_chapter1,26789.108421,0.000000e+00,Reject H0,the difference in the distribution of the obse...
2,tab_chapter2,11019.766350,0.000000e+00,Reject H0,the difference in the distribution of the obse...
3,tab_chapter3,14144.621625,0.000000e+00,Reject H0,the difference in the distribution of the obse...
4,tab_chapter4,101539.618777,0.000000e+00,Reject H0,the difference in the distribution of the obse...
5,tab_chapter5,62211.904463,0.000000e+00,Reject H0,the difference in the distribution of the obse...
6,tab_chapter6,32887.807794,0.000000e+00,Reject H0,the difference in the distribution of the obse...
7,tab_chapter7,14303.288138,0.000000e+00,Reject H0,the difference in the distribution of the obse...
8,tab_chapter8,4975.338873,0.000000e+00,Reject H0,the difference in the distribution of the obse...
9,tab_chapter9,103018.384431,0.000000e+00,Reject H0,the difference in the distribution of the obse...
10,tab_chapter10,64104.023011,0.000000e+00,Reject H0,the difference in the distribution of the obse...
11,tab_chapter11,86956.690300,0.000000e+00,Reject H0,the difference in the distribution of the obse...
12,tab_chapter12,16386.255327,0.000000e+00,Reject H0,the difference in the distribution of the obse...
13,tab_chapter13,93660.011395,0.000000e+00,Reject H0,the difference in the distribution of the obse...
14,tab_chapter14,50545.269241,0.000000e+00,Reject H0,the difference in the distribution of the obse...
15,tab_chapter15,47893.122395,0.000000e+00,Reject H0,the difference in the distribution of the obse...
16,tab_chapter16,61.468927,1.181969e-06,Reject H0,the difference in the distribution of the obse...
17,tab_chapter17,1318.907039,8.317674e-99,Reject H0,the difference in the distribution of the obse...
18,tab_chapter18,172442.354419,0.000000e+00,Reject H0,the difference in the distribution of the obse...
19,tab_chapter19,89434.003124,0.000000e+00,Reject H0,the difference in the distribution of the obse...
20,tab_chapter20,114790.698028,0.000000e+00,Reject H0,the difference in the distribution of the obse...
21,tab_chapter21,150851.496086,0.000000e+00,Reject H0,the difference in the distribution of the obse...

In [4]:
df

    chapter      ED     IPD
13        1   12002  105926
15        2    7808  112388
14        3    9309  171510
4         4   64489  556969
6         5   48131  322429
12        6   15917  182196
17        7    5414   30793
18        8    2962    8284
2         9   95028  732435
10       10   34869  180230
8        11   39539  315114
11       12   18380   61208
5        13   56951  191518
9        14   39200  227362
16       15    6926   74459
20       16       9      59
19       17     355   11472
0        18  252201  370060
1        19   98659  151677
3        20   84982  162558
7        21   46463  731055

In [8]:
def absolute_percentage_difference(ed_count, ipd_count):
    """Calculate the absolute percentage difference between ED and IPD."""
    if (ed_count + ipd_count) == 0:
        return np.nan  # Avoid division by zero
    ed_percentage = (ed_count / (ed_count + ipd_count)) * 100
    ipd_percentage = (ipd_count / (ed_count + ipd_count)) * 100
    return abs(ed_percentage - ipd_percentage)

def risk_ratio(statistic, base):
    """Calculate risk ratio."""
    return statistic / base if base != 0 else np.nan

df["percentage_difference"] = df.apply(lambda row: absolute_percentage_difference(row["ED"], row["IPD"]), axis=1)
df["risk_ratio"] = df.apply(lambda row: risk_ratio(row["ED"], row["IPD"]), axis=1)

In [9]:
df

    chapter      ED     IPD  percentage_difference  risk_ratio
13        1   12002  105926              79.645207    0.113306
15        2    7808  112388              87.007887    0.069474
14        3    9309  171510              89.703516    0.054277
4         4   64489  556969              79.245902    0.115786
6         5   48131  322429              74.022560    0.149276
12        6   15917  182196              83.931393    0.087362
17        7    5414   30793              70.094181    0.175819
18        8    2962    8284              47.323493    0.357557
2         9   95028  732435              77.031481    0.129743
10       10   34869  180230              67.578650    0.193469
8        11   39539  315114              77.702712    0.125475
11       12   18380   61208              53.812132    0.300288
5        13   56951  191518              54.158466    0.297366
9        14   39200  227362              70.588456    0.172412
16       15    6926   74459              82.979665    0.093018
20       16       9      59              73.529412    0.152542
19       17     355   11472              93.996787    0.030945
0        18  252201  370060              18.940445    0.681514
1        19   98659  151677              21.178736    0.650455
3        20   84982  162558              31.338774    0.522780
7        21   46463  731055              88.048380    0.063556

### การตีความผลลัพธ์
หมวดที่มี percentage_difference สูง เช่น 35% อาจ Pratical Significance เนื่องจากสัดส่วนของ IPD สูงกว่ามาก

การตีความค่า RR\
RR > 1 → บ่งบอกว่าผู้ป่วยในหมวดนี้มีแนวโน้มไปรักษาที่ ED มากกว่าที่ IPD\
RR < 1 → บ่งบอกว่าผู้ป่วยในหมวดนี้มีแนวโน้มเข้ารับการรักษาที่ IPD มากกว่า ED\
RR ≈ 1 → ไม่มีความแตกต่างในเชิงปฏิบัติ